name: fuelet_secure_layer
description: "Fuelet wallet secure layer features"
version: 1.0.0

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_fuels: 0.0.34

  flutter_secure_storage: ^7.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.0
  freezed: ^2.3.2
  freezed_annotation: ^2.1.0
  equatable: ^2.0.5

  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  json_serializable: ^6.6.1

flutter:
